on:
  push:
    paths:
      - 'sandbox/*'
      - '.github/workflows/*'
    branches: [master]
  pull_request:
    paths:
      - 'sandbox/*'
      - '.github/workflows/*'
    branches: [master]

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-distribution: 'temurin'
          java-version: '21'
      - name: Build project with Maven
        run: |
          cd sandbox
          mvn -B package --file pom.xml